### ISSUE TITLE
std::int8_t and std::uint8_t numeric field types are not supported.

### ISSUE THREAD

**Issue by GMezWheel** [Stiffstream/json_dto#18]
Why std::int8_t and std::uint8_t numeric field types are not supported ?

I can add missing read/write_json_value functions into pub.hpp but is it the good solution ?

**Comment by eao197** [comment]
Hi!

> Why std::int8_t and std::uint8_t numeric field types are not supported ?

Maybe because json-dto contains the functionality we needed or asked for. We didn't need support for int8/uint8 and nobody asked us until now.

I made some changes to json-dto in issue-18 branch. I'll check them on Windows later today, and if everything will be fine then a new update of json-dto will be released.

**Comment by GMezWheel** [comment]
Thanks, @eao197
