### ISSUE TITLE
NaN values

### ISSUE THREAD

**Issue by qwertynat** [Stiffstream/json_dto#8]
Hi How would one go about dealing with JSON that has optional fields which is a double which can also have "Nan" values

Basically everything works as expected utill i get a JSON value with a Nan. Any help much appreciated! 

Working:
{"id":234, "test": 4.0}

Working :
{"id":235}

Not Working:
{"id":234, "test": "Nan"}

**Comment by eao197** [comment]
Hi! Thanks for reporting that. I'll take a look.

**Comment by eao197** [comment]
Values like `"nan"`, `"inf"` and `"-inf"` are non-standard in JSON. They can be used as non-standard extensions and RapidJson handles them that way:

* a flag `rapidjson::kParseNanAndInfFlag` should be passed to `from_json` function, for example:
```cpp
const auto my_data = json_dto::from_json<MyData, rapidjson::kParseNanAndInfFlag>(str);
```
* RapidJSON recognizes only values `NaN`, `Inf`, or `Infinitiy`. Not `nan`, `Nan`, `inf` or something else. Not `"NaN"` nor `"nan"`, nor `"Nan"`. It means that `{"id":234, "test":"Nan"}` can't be parsed by RapidJSON. Only in that form: `{"id":234, "test":NaN}`.

Because json_dto is just a thin wrapper around RapidJSON it's impossible to parse documents like `{"id":234, "test":"Nan"}` by json_dto.

However, json_dto can be extended by something like:
```cpp
struct MyData {
  int id;
  double test;
  ...
  template<typename Io>
  void json_io(Io & io) {
     io & json_dto::mandatory("id", id)
        & json_dto::mandatory(double_extractor{}, "test", test);
  }
};
```
where `double_extractor` will be something like:
```cpp
struct double_extractor {
  double read(const rapidjson::Value & from) const {
     if(from.IsNumber()) return from.GetDouble();
     if(from.IsString()) {
        const auto * str_v = from.GetString();
        if(0 == strcasecmp(str_v, "nan")) return std::numeric_limits<double>::quiet_NaN();
        ...
     }
     throw json_dto::ex_t{"value is not double"};
  }
  void write(double v, rapidjson::Value & to, rapidjson::MemoryPoolAllocator<> &) const {
    to.SetDouble(v);
  }
};
```
and you have to write such `double_extractor` by yourself.

**Comment by eao197** [comment]
@qwertynat 
Version 0.2.10 with support of custom Reader_Writer types (from an idea described above) is just released. Now you can try to handle non-standard values in JSON document via your Reader_Writer as described [here](https://github.com/Stiffstream/json_dto/tree/v.0.2.10#usage-of-reader_writer).

**Comment by qwertynat** [comment]
niceone! will have a play with it.
